// This file was generated by silverstripe/cow from client/lang/src/en.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('en', {
    "LinkField.SAVE_SUCCESS": "Saved link",
    "LinkField.CONFIRM_ARCHIVE": "Archived link",
    "LinkField.CONFIRM_DELETE": "Deleted link",
    "LinkField.ARCHIVE_ERROR": "Failed to archive link",
    "LinkField.DELETE_ERROR": "Failed to delete link",
    "LinkField.ADD_LINK": "Add Link",
    "LinkField.ARCHIVE": "Archive",
    "LinkField.DELETE": "Delete",
    "LinkField.SAVE_RECORD_FIRST": "Cannot add links until the record has been saved"
  });
}