// This file was generated by silverstripe/cow from client/lang/src/en.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('en', {
    "LinkField.SAVE_SUCCESS": "Saved link",
    "LinkField.ARCHIVE_CONFIRM": "Are you sure you want to archive this link?",
    "LinkField.DELETE_CONFIRM": "Are you sure you want to delete this link?",
    "LinkField.ARCHIVE_SUCCESS": "Archived link",
    "LinkField.DELETE_SUCCESS": "Deleted link",
    "LinkField.ARCHIVE_ERROR": "Failed to archive link",
    "LinkField.DELETE_ERROR": "Failed to delete link",
    "LinkField.ADD_LINK": "Add Link",
    "LinkField.ARCHIVE": "Archive",
    "LinkField.DELETE": "Delete",
    "LinkField.LINK_DRAFT_TITLE": "Link has draft changes",
    "LinkField.LINK_DRAFT_LABEL": "Draft",
    "LinkField.LINK_MODIFIED_TITLE": "Link has unpublished changes",
    "LinkField.LINK_MODIFIED_LABEL": "Modified",
    "LinkField.CANNOT_CREATE_LINK": "Cannot create link",
    "LinkField.FAILED_TO_LOAD_LINKS": "Failed to load links",
    "LinkField.FAILED_TO_SAVE_LINK": "Failed to save link",
    "LinkField.SAVE_RECORD_FIRST": "Cannot add links until the record has been saved",
    "LinkField.SORT_SUCCESS": "Updated link sort order",
    "LinkField.SORT_ERROR": "Unable to sort links"
  });
}