// This file was generated by silverstripe/tx-translator from client/lang/src/pl.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('pl', {
    "LinkField.ADD_LINK": "Dodaj",
    "LinkField.ARCHIVE": "Archiwizuj",
    "LinkField.ARCHIVE_CONFIRM": "Czy na pewno chcesz zarchiwizować ten link?",
    "LinkField.ARCHIVE_ERROR": "Nie udało się połączyć z archiwum",
    "LinkField.ARCHIVE_SUCCESS": "Zarchiwizowany link",
    "LinkField.CANNOT_CREATE_LINK": "Nie można utworzyć linku",
    "LinkField.DELETE": "Usuń",
    "LinkField.DELETE_CONFIRM": "Czy na pewno chcesz usunąć ten link?",
    "LinkField.DELETE_ERROR": "Nie udało się usunąć linku",
    "LinkField.DELETE_SUCCESS": "Skasowano link",
    "LinkField.EDIT_LINK": "Zmień",
    "LinkField.FAILED_TO_LOAD_LINKS": "Nie udało się załadować link(ów)",
    "LinkField.FAILED_TO_SAVE_LINK": "Nie udało się zapisać linku",
    "LinkField.LINK_DRAFT_LABEL": "Szkic",
    "LinkField.LINK_DRAFT_TITLE": "Link ma zmiany w szkicu",
    "LinkField.LINK_MODIFIED_LABEL": "Zmodyfikowane",
    "LinkField.LINK_MODIFIED_TITLE": "Link ma niepublikowane zmiany",
    "LinkField.SAVE_RECORD_FIRST": "Nie można dodawać linków, dopóki rekord nie zostanie zapisany",
    "LinkField.SAVE_SUCCESS": "Zapisano",
    "LinkField.SORT_ERROR": "Nie można sortować linków",
    "LinkField.SORT_SUCCESS": "Zaktualizowana kolejność sortowania linków"
});
}