// This file was generated by silverstripe/tx-translator from client/lang/src/sv.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sv', {
    "LinkField.ADD_LINK": "Lägg till länk",
    "LinkField.ARCHIVE": "Arkiv",
    "LinkField.ARCHIVE_CONFIRM": "Är du säker på att du vill arkivera denna länk?",
    "LinkField.ARCHIVE_ERROR": "Misslyckades att arkivera länken",
    "LinkField.ARCHIVE_SUCCESS": "Arkiverad länk",
    "LinkField.CANNOT_CREATE_LINK": "Kunde inte skapa länken",
    "LinkField.DELETE": "Radera",
    "LinkField.DELETE_CONFIRM": "Är du säker att du vill radera denna länk?",
    "LinkField.DELETE_ERROR": "Misslyckades att radera länken",
    "LinkField.DELETE_SUCCESS": "Raderade länken",
    "LinkField.EDIT_LINK": "Redigera länk",
    "LinkField.FAILED_TO_LOAD_LINKS": "Misslyckade att ladda länk(ar)",
    "LinkField.FAILED_TO_SAVE_LINK": "Misslyckades att spara länken",
    "LinkField.LINK_DRAFT_LABEL": "Utkast",
    "LinkField.LINK_DRAFT_TITLE": "Länk har ändringar i utkast",
    "LinkField.LINK_MODIFIED_LABEL": "Ändrad",
    "LinkField.LINK_MODIFIED_TITLE": "Länk har opublicerade ändringar",
    "LinkField.SAVE_RECORD_FIRST": "Kan inte lägga till länkar före detta har sparats",
    "LinkField.SAVE_SUCCESS": "Sparade länk",
    "LinkField.SORT_ERROR": "Misslyckades att sortera länkar",
    "LinkField.SORT_SUCCESS": "Uppdaterade länk sorteringsorder"
});
}